// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("EditorConfig.VisualStudio")]
[assembly: AssemblyProductAttribute("EditorConfig.VisualStudio")]
[assembly: AssemblyDescriptionAttribute("Loads editor options such as indentation sizes from standard, cross-platform .editorconfig files on a per project/solution basis.")]
[assembly: AssemblyVersionAttribute("0.6.0")]
[assembly: AssemblyFileVersionAttribute("0.6.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.6.0";
    }
}
